/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  separator?: string
  transform?: number
}
export function slugize(str: Buffer | string, options?: Options | undefined | null): string
export function stripTags(htmlContent: Buffer | string): string
