/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function stripTags(htmlContent: Buffer | string): string
export interface Options {
  length?: number
  omission?: string
  separator?: string
}
export function truncate(str: string | Buffer, options?: Options | undefined | null): string
