/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function decodeUrl(url: string): string
export function encodeUrl(url: string): string
export function escapeDiacritic(input: string): string
export function escapeHtml(input: Buffer | string): string
export function escapeRegExp(input: string): string
export function isExternalLink(
  url: string,
  sitehost: string,
  exclude?: string | Array<string> | undefined | null,
): boolean
export interface SlugizeOptions {
  separator?: string
  transform?: number
}
export function slugize(str: Buffer | string, options?: SlugizeOptions | undefined | null): string
export function stripTags(htmlContent: Buffer | string): string
export function unescapeHtml(input: Buffer | string): string
export interface WordWrapOptions {
  width: number
}
export function wordWrap(s: string, options?: WordWrapOptions | undefined | null): string
